spring:
  application:
    name: sau-vibe
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sau_vibe}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:189919}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
  weather:
    api-key: ${OPENWEATHER_API_KEY:7674c4af7ade4eb88e46f5fafc616044}
  agent:
    api-url: ${AGENT_API_URL:http://127.0.0.1:8000}
  admin-key: ${ADMIN_KEY:admin}